# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'immotchat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Messaging'

  # Pods for immotchat

  target 'immotchatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'immotchat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for immotchat-tvOS

  target 'immotchat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
